### ISSUE TITLE
add a readme

### ISSUE THREAD

**Issue by ORESoftware** [chrisdrobison/oplog-tail#1]
add a readme

**Comment by chrisdrobison** [comment]
Describing what?

**Comment by ORESoftware** [comment]
exactly :)

**Comment by ORESoftware** [comment]
Github, when you look at it, is a public place to share code with others. OSS, and all that good stuff. To help others steal your code, it helps if there is a readme that at least tells people what it's about so they can decide if they want to dig deeper or not

**Comment by chrisdrobison** [comment]
I'll leave the digging to you as this is a tiny repo solely created to help debug and issue with the developers at Mongo. Feel free to use it or not.
